name: Publish and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-artifact
        path: ./publish
